import 'dart:ui';

const primaryColor = Color(0XFF083E9E);
const accentColor = Color(0XFF06446F);
const cardColor1 = Color(0XFF4770B9);
const cardColor2 = Color(0XFF471C7E);
const cardColor3 = Color(0XFFD94E05);
const addNewCardBg = Color(0XFFCDD8EB);
const fundWalletBg = Color(0XFFCCE4CD);
const withdrawBg = Color(0XFFE9CCCC);
const greyShade1 = Color(0XFF8D8D8D);
const greyShade2 = Color(0XFFCFCFCF);
const masterRed = Color(0XFFEA001B);
const masterYellow = Color(0XFFF79E1C);
var hoverColor = const Color(0XFF083E9E).withOpacity(0.1);
const makeSubBg = Color(0XFFE0F2FF);
const makeNewPlanBg = Color(0XFFF9EBCD);
const manageSubColor = Color(0XFFF4CDEB);
const changeCurrencyBg = Color(0XFFEEF8FF);
const successColor = Color(0XFF10CC68);
const errorColor = Color(0XFFFF7D81);